services:
    #Postgrace Services
    postgres:
        image: docker.io/postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #Redis Services
    redis:
        image: docker.io/redis
        command: ["redis-server", "--protected-mode", "no"]
    #API Services
    api:
        build:
            context: ./server
        image: docker.io/sirkitbreaker/complex_api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #Worker Service
    worker:
        build: ./worker
        image: docker.io/sirkitbreaker/complex_worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    #React client
    client:
        build: ./client
        image: docker.io/sirkitbreaker/complex_client
    #Nginx Web Server
    ngnix:
        depends_on:
            - api
            - client
        build: ./nginx
        ports:
            - "8082:80"
